[package]
name = "example_server"
version = "0.1.0"
edition = "2021"

[dependencies]
nah_server = {path="../nah_server"}
nah_mcp_types = {path="../nah_mcp_types"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
