[package]
name = "nah_server"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
nah_mcp_types = { path="../nah_mcp_types" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.41"